# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'ReactivePractice1' do
pod 'ReactiveCocoa', '2.4.7'
end

target 'ReactivePractice1Tests' do

end

